[package]
name = "routeguide_rust_client"
version = "0.1.0"
edition = "2021"

[workspace]

[lib]
name = "routeguide_rust_client"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module", "abi3-py39"] }
pyo3-asyncio = { version = "0.20", features = ["tokio-runtime"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
tonic = { path = "../../../../tonic" }
tonic-prost = { path = "../../../../tonic-prost" }
prost = "0.14"

[build-dependencies]
tonic-prost-build = { path = "../../../../tonic-prost-build" }
